# Generated by Django 5.0 on 2023-12-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('daw', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
