# Generated by Django 5.0 on 2023-12-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_store', '0004_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
